name: Bounty
version: '${version}'
main: net.malusic.bounty.PluginLoader
api-version: '26.2'
description: Simple liteweight minecraft bounty system
author: Malusic
depend: [Vault]
commands:
  bounty:
    description: Manage player bounties
    usage: /bounty <set|remove|bet|check|reload>
permissions:
  bounty.set:
    description: Allows setting player bounties
    default: op
  bounty.remove:
    description: Allows removing player bounties
    default: op
  bounty.reload:
    description: Allows reloading bounty messages
    default: op
  bounty.bet:
    description: Allows adding money to bounties
    default: true