name: Bounty
version: 1.0
main: net.malusic.bounty.PluginLoader
api-version: 26.2
description: Simple liteweight minecraft bounty system
author: Malusic
commands:
  bounty:
    description: Manage player bounties
    usage: /bounty <set|remove|bet|check|reload>
permissions:
  bounty.reload:
    description: Allows reloading the bounty messages
    default: op
  bounty.set:
    description: Allows overriding the bounty
    default: op
  bounty.remove:
    description: Allows removing the bounty
    default: op